### ISSUE TITLE
Flagging functionally not working.

### ISSUE THREAD

**Issue by gateway** [Factual/factual-php-driver#36]
The code from the main page for flagging does not seem to work when adding our key and secret.

```
    //get started
    require_once('Factual.php');
    $factual = new Factual($key,$secret);
    //create a new flagger object to hold our parameters
    $flagger = new FactualFlagger;
    //add required parameters
    $flagger->setFactualID("f33527e0-a8b4-4808-a820-2686f18cb00c"); //ID to check
    $flagger->setTableName("2EH4Pz"); //name of table
    $flagger->setUserToken("testUser"); //arbitrary token of individual user
    $flagger->setProblem("duplicate");
    //add optional parameters
    $flagger->setComment("Found by user");
    $flagger->setReference("Original entity on http://example.com");
    //make request
    $res = $factual->flag($flagger);
    //check for success
    if ($res->success()){
        echo "OK\n";
    } else {
        echo "Borked\n";
    }
```

It throws an error 

```
2016/06/15 23:23:06 [error] 3738#0: *4380 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'FactualApiException' with message 'Requested resource could not be found.' in /var/www/tests/factual/factual-php-driver/Factual.php:542
Stack trace:
#0 /var/www/tests/factual/factual-php-driver/Factual.php(332): Factual->request('http://api.v3.f...', 'POST', Array)
#1 /var/www/tests/factual/submit.php(18): Factual->flag(Object(FactualFlagger))
#2 {main}
  thrown in /var/www/tests/factual/factual-php-driver/Factual.php on line 542" while reading response header from upstream, client: 12.215.39.106, server: myserver.com, request: "GET /tests/factual/submit.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "myserver.com"
```

Any help with this?

**Comment by gateway** [comment]
Stepping though and printing out what the curl request is trying to send.

```
Array
(
    [code] => 404
    [headers] => Array
        (
            [access-control-allow-origin] => *
            [cache-control] => max-age=0
            [content-type] => application/json; charset=utf-8
            [date] => Wed, 15 Jun 2016 23:42:09 GMT
            [vary] => Accept-Encoding
            [content-length] => 101
            [connection] => keep-alive
        )

    [body] => {"version":3,"status":"error","error_type":"Auth","message":"Requested resource could not be found."}
)
Array
(
    [10023] => Array
        (
            [0] => X-Factual-Lib: factual-php-driver-v1.5.8
            [1] => Content-Type: application/x-www-form-urlencoded
        )

    [78] => 0
    [13] => 0
)
```

**Comment by gateway** [comment]
Ok this is resolved, you should update the documents.. the table name example you have if somewhere would be to past the code is invalid, not even sure why its "2EH4Pz" this should be "places"
